{  //2022.6.13
    "author": "尤东风",
    "ua": "",
    "homeUrl": "https://www.366ys.cc/",
    "dcVipFlag": "true",
    "pCfgJs": "https://www.366ys.cc/static/js/playerconfig.js",
    "pCfgJsR": "[\\W|\\S|.]*?MacPlayerConfig.player_list[\\W|\\S|.]*?=([\\W|\\S|.]*?),MacPlayerConfig.downer_list",
    "dcShow2Vip": {},
    "dcPlayUrl": "true",
    //"cateNode": "//div[contains(@class,'head_menu_a')]/ul[contains(@class, 'top_nav clearfix')]/li/a[contains(@href,'vodtype')]",
    //"cateName": "/text()",
    //"cateId": "/@href",
    "cateIdR": "/vodshow/(\\d+)/",
    "cateManual": {"电影": "1","电视剧": "2","综艺": "3","动漫": "4"},
    "cateUrl": "https://www.366ys.cc/vodshow/{cateId}--------{catePg}---.html",
    "cateVodNode": "//div[contains(@class, 'stui-pannel')]//a[@class='stui-vodlist__thumb lazyload']",
    "cateVodName": "/@title",
    "cateVodId": "//@href",
    "cateVodIdR": "/y/(\\w+).html",
    "cateVodImg": "//@data-original",
    "cateVodImgR": "\\S+(http\\S+)",
    "cateVodMark": "//span[@class='pic_text text_right']/text()",
    "dtUrl": "https://www.366ys.cc/y/{vid}.html",
    "dtNode": "//body",
    "dtName": "//div[@class='stui-content__thumb']/a[@class='pic']/@title",
    "dtImg": "//div[@class='stui-content__thumb']/a[@class='pic']/img/@data-original",
    "dtArea": "//p[contains(text(), '地区')]/text()",
	"dtAreaR": "",
    //"dtYear": "//p[contains(text(), '年份')][4]/text()",
    //"dtCate": "//p[contains(text(), '类型')]/text()",
    //"dtDirector": "//p[contains(text(), '导演')]/following-sibling::a/text()",
    "dtDirector": "//p[(@class='data') and contains(text(), '导演')]/a/text()",
    "dtActor": "//p[(@class='data') and contains(text(), '主演')]/a/text()",
    "dtActorR": "\\S+主演：(\\S+)",
    //"dtMark": "//div[@class='video-info-item'][1]/text()",
    "dtDesc": "//p[@class='desc detail']/span[2]/text()",
    "dtFromNode": "//div[@class='stui-vodlist__head']//ul[contains(@class, 'nav nav-tabs  dpplay pull-right')]/li/a",
    "dtFromName": "/text()",
    "dtUrlNode": "//div[contains(@class, 'stui-vodlist__head')]//ul[contains(@class,'stui-content__playlist clearfix ')]",
    "dtUrlSubNode": "/li/a",
    "dtUrlId": "@href",
    "dtUrlIdR": "/k/(\\S+).html",
    "dtUrlName": "/text()",
    "dtUrlNameR": "",
    "playUrl": "https://www.366ys.cc/k/{playUrl}.html",
    "playUa": "",
    "searchUrl": "https://www.366ys.cc/index.php/ajax/suggest?mid=1&wd={wd}&limit=10",
    "scVodNode": "json:list",
    "scVodName": "name",
    "scVodId": "id",
    "scVodIdR": "",
    "scVodImg": "pic",
    "scVodMark": ""
}