{
    "ua": "",
    "homeUrl": "https://www.diezz.net/",
    //"dcVipFlag": "true",
    //"pCfgJs": "https://www.diezz.net/static/js/playerconfig.js",
    //"pCfgJsR": "[\\W|\\S|.]*?MacPlayerConfig.player_list[\\W|\\S|.]*?=([\\W|\\S|.]*?),MacPlayerConfig.downer_list",
    //"dcShow2Vip": {},
    //"dcPlayUrl": "true",
    "cateNode": "//div[contains(@class,'head_menu_a')]/ul[contains(@class,'top_nav clearfix')]//li/a[contains(@href, 'vodtype')]",
    "cateName": "/text()",
    "cateId": "/@href",
    "cateIdR": "",
    "cateManual": {"电影": "1","连续剧": "2","综艺": "3","动漫": "4"},
    "homeVodNode": "//ul[contains(@class,'vodlist vodlist_wi')]/li/a[contains(@class, 'vodlist_thumb lazyload')]",
    "homeVodName": "/@title",
    "homeVodId": "/@href",
    "homeVodIdR": "/v/(\\s+).html",
    "homeVodImg": "/@data-original",
    "homeVodMark": "",
    "cateUrl": "https://www.diezz.net/vodshow/{cateId}---{catePg}---.html",
    "cateVodNode": "//div[contains(@class,'pannel clearfix')]/ul[contains(@class,'vodlist vodlist_wi clearfix')]/li/a",
    "cateVodName": "/@title",
    "cateVodId": "/@href",
    "cateVodIdR": "/v/(\\s+).html",
    "cateVodImg": "/@data-original",
    "cateVodMark": "/span[contains(@class,'pic_text text_right')]/text()",
    "dtUrl": "https://www.diezz.net/v/{vid}.html",
    "dtNode": "//body//div[contains(@class,'content_box clearfix')]",
    "dtName": "//div[contains(@class,'pannel_head clearfix')]/h2[contains(@class,'title')]/text()",
    "dtImg": "//div[contains(@class,'content_thumb fl')]/a[contains(@class,'vodlist_thumb lazyload')]/@data-original",
    "dtImgR": "",
    "dtCate": "//span[contains(text(),'类型')]/following-sibling::*/text()",
    "dtYear": "//span[contains(text(),'年份')]/following-sibling::*/text()",
    "dtArea": "//span[contains(text(),'地区')]/following-sibling::*/text()",
    "dtDesc": "//span[contains(text(),'简介')]/following-sibling::*/text()",
    "dtFromNode": "//div[contains(@class,'play_source')]/div/a",
    "dtFromName": "/@alt",
    "dtUrlNode": "//div[contains(@class,'playlist_full')]/ul[contains(@class,'content_playlist clearfix')]",
    "dtUrlSubNode": "/li/a",
    "dtUrlId": "/@href",
    "dtUrlIdR": "/play/(\\d+).html",
    "dtUrlName": "/text()",
    "playUrl": "https://www.diezz.net/play/{playUrl}.html",
    "searchUrl": "https://www.diezz.net/index.php/ajax/suggest?mid=1&wd={wd}&limit=10",
    "scVodNode": "json:list",
    "scVodName": "name",
    "scVodId": "id",
    "scVodIdR": "",
    "scVodImg": "pic",
    "scVodMark": ""
}